### ISSUE TITLE
TypeError: placeholder.indexOf is not a function

### ISSUE THREAD

**Issue by elrumordelaluz** [bluebill1049/react-simple-img#104]
**Describe the bug**
Declaring a `placeholder` using `require` gives the error shown in the title.

**To Reproduce**
1. Go to [this sandbox](https://codesandbox.io/s/wonderful-star-cc4os?file=/src/App.js:236-279)
2. Look that declaring `require('./images/cover.svg')` throws an error.
3. Commenting this line shows that this doesn't happen with the `src` prop

**Expected behavior**
This used to word until I updated to `create-react-app@4` (which implies to remove `node_modules` folder and reinstall dependencies, so maybe is related to another change). But seems that the error reproduce well in _Codesandbox_

**Screenshots**
<img width="1125" alt="Screenshot 2020-10-26 at 12 20 03" src="https://user-images.githubusercontent.com/784056/97166532-b1711700-1785-11eb-93b3-05478c6e83ea.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser _Firefox_
 - Version 81.0.2 (64-bit)

**Additional context**
I know that work ok just `import`ing the two files, but in my case I am using several images that render dynamically so i used to pass the values like `require('./images/image_' + n + '.svg')`

**Comment by bluebill1049** [comment]
I don't think we support `reqiure` import.

**Comment by elrumordelaluz** [comment]
Thank you @bluebill1049, however for some reason works perfect for me (also in `react@17`), before update `react-scripts`.

**Comment by elrumordelaluz** [comment]
Ok, I solved this way

```js
<SimpleImg
  placeholder{require(`./path/to/img`).default}
/>
```

Don't know where is the root of the problem, probably _bundler_ side. Will continue to investigate however.

**Comment by bluebill1049** [comment]
interesting... I suspect it returns a string now.

**Comment by elrumordelaluz** [comment]
yes, also before returns a `string` but for some reason without needed the `.default`.
