### ISSUE TITLE
Duplicate babel-polyfill error

### ISSUE THREAD

**Issue by dustinkerstein** [bluebill1049/react-simple-img#15]
I use babel-polyfill in my app and this seems to cause the following error: 

`only one instance of babel-polyfill is allowed`

If I remove my require(babel-polyfill) then I can get react-simple-img working, but other parts of my app break and I haven't figured out why. Is it possible to remove this dependency from react-simple-img?

**Comment by bluebill1049** [comment]
Hey Dustin,

let me take a look that, i will see what i can do to solve that.

cheers
bill

**Comment by bluebill1049** [comment]
Hey Dustin,

please try react-simple-img@1.3.5

let me know if that's all good.

thanks

**Comment by dustinkerstein** [comment]
Just gave 1.3.5 a quick try and it seems to behave the same way. Anything else I can get you as far as debug goes?

**Comment by bluebill1049** [comment]
Thanks for the checking, i guess i have to do the following 

```if (!global._babelPolyfill && !window._babelPolyfill) { 
  require("babel-polyfill");
}```

will let you know once published

**Comment by dustinkerstein** [comment]
Nice! That seems to do the trick.

**Comment by bluebill1049** [comment]
cool thanks i will close it then :)
