### ISSUE TITLE
Support for fixed size blank placeholder

### ISSUE THREAD

**Issue by dustinkerstein** [bluebill1049/react-simple-img#17]
I've got things working almost perfectly, but the one thing that would really add the final touch of polish for my use-case would be the ability to get the placeholder aspect ratio correct before the image loads. In my app I can't control the individual image sizes, but I do have access to the dimensions before downloading.

I tried to implement this using a dynamically sized SVG via:

`const customSVG = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="800" height="' + relativeHeightPixels + 'px"><rect x="0" y="0" width="800" height="' + relativeHeightPixels + 'px" fill="white" /></svg>'`

Here is how I'm calling SimpleImg:

`<SimpleImg className="col col-12" height={relativeHeightString} width={"100%"} src={moment.thumb_url ? moment.thumb_url : PanoMoments.assets.placeholder} />`

And this works great in Chrome/Safari/Firefox, but it seems there is a bug with Edge where it never changes the opacity. I could detect the browser and not render like this for Edge, but I'd be a little worried that the opacity issue isn't as isolated as I may hope it to be. Do you see an alternative way to achieve what I'm looking for?

**Comment by bluebill1049** [comment]
hmmm not sure about this one mate.

**Comment by dustinkerstein** [comment]
K, no worries. I'll go ahead and close this as it's definitely not an issue with react-simple-img.
