### ISSUE TITLE
Dependency issue installing via Yarn

### ISSUE THREAD

**Issue by dustinkerstein** [bluebill1049/react-simple-img#18]
I have no issues when installing via NPM, but with Yarn I get:

```
$ yarn add react-simple-img@beta
yarn add v0.24.5
warning pano_moments@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-simple-img@1.3.6-beta.1" has incorrect peer dependency "react@>=15.6.1".
warning "react-simple-img@1.3.6-beta.1" has incorrect peer dependency "react-dom @>= 15.6.1".
warning "react-simple-img@1.3.6-beta.1" has unmet peer dependency "prop-types@^1 5.6.0".
warning "react-simple-animate@1.9.0" has incorrect peer dependency "react@>= 15. 6.1".
warning "react-simple-animate@1.9.0" has incorrect peer dependency "react-dom@>= 15.6.1".
[4/4] Building fresh packages...
success Saved 0 new dependencies.
warning pano_moments@1.0.0: No license field
Done in 15.37s.
```

Which results in this error:

`Error: Cannot find module 'prop-types'`

**Comment by bluebill1049** [comment]
i have moved prop-types out from peer dependencies 1.3.6-beta.2.

hopefully i get sometimes to upgrade with the new context API, so prop-types can be removed.

let me know if that fix your issue

**Comment by dustinkerstein** [comment]
Cool, will try to give this a try tomorrow.

**Comment by dustinkerstein** [comment]
I seem to get this error on the latest beta:

`Uncaught ReferenceError: regeneratorRuntime is not defined`

**Comment by bluebill1049** [comment]
what about 1.3.6?

**Comment by dustinkerstein** [comment]
What's the tag name for that? I think I tried the latest beta.

**Comment by bluebill1049** [comment]
that's latest version mate. 1.3.6 no beta

**Comment by dustinkerstein** [comment]
Is it in both npm and Yarn repos?

**Comment by bluebill1049** [comment]
yea

**Comment by dustinkerstein** [comment]
This is what I see in when adding via Yarn:

![image](https://user-images.githubusercontent.com/7659306/39480987-c6c03840-4d1e-11e8-8e01-ef740f012e2a.png)

Do you mean the beta2?

**Comment by bluebill1049** [comment]
Hmm I will

**Comment by bluebill1049** [comment]
closed by accident, forgot to publish 1.3.6

**Comment by bluebill1049** [comment]
your issue could be babel polyfill version 
this is the version i have in react simple img:    "babel-polyfill": "^6.26.0"
made it peer dependency. hope this will resolve the issue.

**Comment by dustinkerstein** [comment]
Just upgraded to 1.3.7 and looking good so far. Thanks!
