### ISSUE TITLE
Isomorphic/universel js

### ISSUE THREAD

**Issue by millette** [bluebill1049/react-simple-img#26]
I tried to build a site with Gatsby v2 (React static site generator). While it worked in dev, came build time I had an error because of ```window``` being undefined (server-side).

There was an easy workaround:

```js
if (typeof window !== 'undefined') {
  initSimpleImg({ threshold: 0.5 })
}
```

**UPDATE**: my workaround was too simple. It only works if I load the page directly, not if I load another page first and then navigate to my page with lazy loaded images. Although initSimpleImg() is called in page-2, when I load page-1 I see a console output where it's called. In my case, I use SimpleImg in a component which is used by page-2, I have to figure out (with the HOC maybe) how to handle that.

Example:

* [page-1](https://millette.github.io/gatsby-starter-location-github/en/), no images
* [page-2](https://millette.github.io/gatsby-starter-location-github/en/page-2/), with images

I'd like to submit a patch to support client/server detection directly in your module. Interested?

**Comment by bluebill1049** [comment]
hey @millette,

Can you call `initSimpleImg` at client entry file (eg. index.js where you call `ReactDOM.render()`)? 

thanks

**Comment by bluebill1049** [comment]
yes interested your patch to support client/server! ❤️

**Comment by millette** [comment]
Hmm, after digging around a bit, I can't promise anything right now. It's my first real Gatsby project (with v2, in beta) and I'm not exactly sure how the pieces fit. Also, I have to finish my project soon (first).

**Comment by bluebill1049** [comment]
no worries @millette i will take a look the provider issue over the weekend anyhow. cheers

**Comment by bluebill1049** [comment]
i will make a patch on this soon as well 🙏 thanks for reporting.

**Comment by bluebill1049** [comment]
ok i have updated the `initSimpleImg()` method to be run only on the server. issue will be closed in the next couple days, if no issue reports :)

**Comment by millette** [comment]
I was able to remove my ```typeof window``` workaround, thanks again :-)

Taking the liberty to close this issue as it's easier to understand.
