### ISSUE TITLE
Example with multiple components

### ISSUE THREAD

**Issue by millette** [bluebill1049/react-simple-img#27]
I tried a few things to get it working, but I'm not there yet (see #26).

## Example

I have a ```Page``` (component) and another component representing a ```User```. The  ```Page``` will show a colleciton of ```User``` components.

If I add the following to ```Page.js```

```
import { SimpleImg, SimpleImgProvider } from 'react-simple-img'

class Page {
  // ...

 render () {
  return this.props.users.map((user) => <User {...user} SimpleImg={SimpleImg} />)
}
}

export default SimpleImgProvider(Page, { threshold: 0.5 })
```

And in ```User.js``` I use props.SimpleImg, the images are never updated, only the placeholder is shown.

**Comment by millette** [comment]
I tried with ```initSimpleImg()``` running top-level in ```Page.js``` and separately in ```User.js```. It works perfectly using Gatsby v2 in dev, but when I build it, the images only update if I start on ```Page```, not if I first load another page.

**Comment by bluebill1049** [comment]
I will take a look the `provider` issue soon over the weekend. To be honest i probably need to update the context API too.

**Comment by bluebill1049** [comment]
Hi @millette i have updated with a patch to fix the provider bug :)

**Comment by yusinto** [comment]
Nice work thank you

**Comment by millette** [comment]
Don't worry too much about my comments, as I said, I'm just getting started with Gatsby and my React Fu isn't the greatest either. Also, I found out gatsby has it's own image lazy loader, but I'm not 100% sure it would be effective in my case.

I found using your component to be very simple and effective. For instance, this turned out rather well: <https://rollo-venezuela-wtmknramwg.now.sh/> :-)

**Comment by bluebill1049** [comment]
hey @millette, 

lovely demo! i am glad it worked for you! i checked your code for working on per component you probably should use `provider`. but if it worked for you with previous patch, that's all it matters. 😄 

thanks
bill

**Comment by bluebill1049** [comment]
ok i have made a new patch this should be fixed now (1.3.16), going to close the issue in the next couple days, if nothing reports :) thanks

**Comment by millette** [comment]
Looking good on my end. As I mentionned, last patch broke it for me, but with this one, my project works again. Thanks!

P.S.: I will eventually revisit my code to make proper use of ```provider```.

**Comment by bluebill1049** [comment]
👍 thanks @millette
