### ISSUE TITLE
Support for custom options

### ISSUE THREAD

**Issue by k-prashant** [bluebill1049/react-simple-img#36]
How should we add  `crossorigin="anonymous"` ?

**Comment by bluebill1049** [comment]
If you have time you can do a PR.
https://github.com/bluebill1049/react-simple-img/blob/master/src/simpleImg.js

otherwise i will allow any custom options on the next path over the weekend.

**Comment by k-prashant** [comment]
won't be possible for me, can you please do it, whenever possible.

**Comment by bluebill1049** [comment]
sure i will get a patch over the weekend.

**Comment by bluebill1049** [comment]
i have published a beta version, could you please test it out `react-simple-img@1.4.6-beta.1`?

and PR is here, if you want to take a look
https://github.com/bluebill1049/react-simple-img/pull/37

**Comment by k-prashant** [comment]
Added a [comment](https://github.com/bluebill1049/react-simple-img/pull/37#issuecomment-452985082).

**Comment by bluebill1049** [comment]
resolved by https://github.com/bluebill1049/react-simple-img/releases/tag/v1.5.1
