### ISSUE TITLE
animationDuration not working

### ISSUE THREAD

**Issue by bar0191** [bluebill1049/react-simple-img#39]
Hello! Awesome component. I noticed however that the animation transition doesn't seem to be working, I install react-simple-animation as well to see if that would fix it. But still got nothing. 

Anyone else had this issue?

**Comment by bluebill1049** [comment]
Thanks heaps :) @bar0191 which version you have right? i had fixed a bug couple days ago with a patch.

**Comment by bluebill1049** [comment]
do you mean duration or just the animation is completely not working at all?

**Comment by bar0191** [comment]
it seems like the animation just isn't working at all, the placeholder will flash out, and I set the animationDuration to something high like 10s and noticed it didn't work. 

I'm on version 1.5.4

**Comment by bluebill1049** [comment]
try 1.5.4 i have fixed it ❤️

**Comment by bluebill1049** [comment]
hmmm... can i have a look at your code snippet?

**Comment by bar0191** [comment]
sooo with a little more testing, the component is fine! It's a HOC I have wrapped around the image component that's making the animation not trigger

**Comment by bar0191** [comment]
Closing this since it looks like I just had to fix some css issues. Sorry for the troubles!

**Comment by bluebill1049** [comment]
haha no worries 👍
