### ISSUE TITLE
Img width: 100% height: auto

### ISSUE THREAD

**Issue by humbertqz** [bluebill1049/react-simple-img#42]
Is there a way to use the component without the wrapping div with flexbox styling and fixed height?

I'm using in the img tag width: 100%; height: auto; to make my image responsive.

**Comment by bluebill1049** [comment]
The `div` is made for the placeholder animation, because you have the actual image and placeholder wrapped inside.

There are two solutions:

1. provide img `width` and `height` and apply `applyAspectRatio` 
2. i will have to create a minor version, by supply `placeholder` = `false`, which will remove placeholder and the wrapping `div`, plus you will lost the animation from the placeholder.

let me know.

**Comment by humbertqz** [comment]
Maybe that could be a feature? 

Remove everything but the img tag.

**Comment by bluebill1049** [comment]
sure i can looking into that over the weekend :) but you lost beautiful animation 👍

**Comment by humbertqz** [comment]
Nice, thanks. 😄

**Comment by bluebill1049** [comment]
Could you please help on testing? `react-simple-img@1.14.0-beta.1`

**Comment by humbertqz** [comment]
Yes!, but i never used a beta repo, how can i download it? I was using the component in a GatsbyJs project.

**Comment by bluebill1049** [comment]
just `yarn add react-simple-img@1.14.0-beta.1` or `npm i react-simple-img@1.14.0-beta.1`. i did testing with my own demo and it works, just want to double check with yours before publishing.

**Comment by humbertqz** [comment]
Yes, it works this is my component: 

`<SimpleImg height={440} src={this.props.imgsrc} placeholder={false} />`

This is what is rendered:

`<img src="/static/thumb-plaza-cataluna-6106ec93376385a64fbf1cd99450ec09.jpg" srcset="" data-placeholder="false" data-src="/static/thumb-plaza-cataluna-6106ec93376385a64fbf1cd99450ec09.jpg" height="440" style="transition: all 0.3s ease 0s; opacity: 0; visibility: visible;">`

Set the opacity: 0; by default, is there a way to change this?

**Comment by bluebill1049** [comment]
i will make it so you can use `style` to overwrite it.

**Comment by bluebill1049** [comment]
try this version react-simple-img@1.14.0-beta.2, thanks for testing.

**Comment by bluebill1049** [comment]
thanks for the testing! i forgot to set opacity back to 1 for the animation :(

try this version react-simple-img@1.14.0-beta.3

should only render <img /> and animate when finished loading

**Comment by humbertqz** [comment]
It's working this is the rendered element:

`<img src="/static/thumb-plaza-cataluna-6106ec93376385a64fbf1cd99450ec09.jpg" srcset="" data-placeholder="false" data-src="/static/thumb-plaza-cataluna-6106ec93376385a64fbf1cd99450ec09.jpg" data-end-style="opacity:0;" style="transition: all 0.3s ease 0s; opacity: 1; visibility: visible;">`

**Comment by bluebill1049** [comment]
thanks @humbertqz will publish today! thank you for your testing ❤️

**Comment by bluebill1049** [comment]
v1.14.0 released, i will close the issue. feel free to re-open if you find other issues 👍
