### ISSUE TITLE
[Request] How about adding `event hook` to SimpleImg element?

### ISSUE THREAD

**Issue by JaeYeopHan** [bluebill1049/react-simple-img#46]
## Description

like this:

```js
<SimpleImg
  height={500}
  placeholder="linear-gradient(rgb(30, 87, 153) 0%, rgb(125, 185, 232) 100%)"
  src="your image path"
  // event listener
  on={() => console.log('image visible')}
  once={() => console.log('image loaded')}
/>
```

### Why?

If need to restore scroll, have to know timing that image loaded.

### Reference

- https://github.com/hilongjw/vue-lazyload#event-hook

**Comment by bluebill1049** [comment]
hey @JaeYeopHan,

Yes can be done, probably will be the next minor update. I am working one of the issue at the moment. 

cheers
bill

**Comment by JaeYeopHan** [comment]
`onComplete` is awesome! Thanks!

**Comment by bluebill1049** [comment]
👍 will try to work this over the weekend

**Comment by bluebill1049** [comment]
want to try this beta version and test?

`react-simple-img@2.0.0-beta.2`

`onComplete` is the prop name

**Comment by bluebill1049** [comment]
The have been baked in the latest release, with onComplete props. feel free to re-open if you found issue.
