### ISSUE TITLE
Doesn't support under react 16.3

### ISSUE THREAD

**Issue by tom76kimo** [bluebill1049/react-simple-img#48]
Since using `React.createRef` [here](https://github.com/bluebill1049/react-simple-img/blob/master/src/simpleImg.js#L31) and it's only provided from react 16.3. We should either remove this or update `peerDependency` in `package.json`

**Comment by bluebill1049** [comment]
thank you @tom76kimo i have updated the `package.json` 👍

**Comment by tom76kimo** [comment]
Great! thanks
