### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by Argeare5** [bluebill1049/react-simple-img#51]
Error in IE:
"The object does not support the "startsWith" property or method."
How can I fix this without changing your code?

**Comment by bluebill1049** [comment]
Which IE version?

**Comment by bluebill1049** [comment]
i am happy to change startWidth to indexOf, but depend on which version of IE. it may not work as well as modern browsers.

**Comment by Argeare5** [comment]
IE 11
startWidth not support in all IE versions
maybe polyfill will help?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill

**Comment by bluebill1049** [comment]
i have updated the code to use `indexOf` instead of `startsWith` 

https://github.com/bluebill1049/react-simple-img/releases/tag/2.1.7

would you mind to star the repo to support this package?  :) (if not no hard feeling too) thanks

**Comment by Argeare5** [comment]
Oh thanks. Now it works in IE! Of course I put a star. I really liked this package, it is easy to use :).
Thanks for the quick fix.

**Comment by bluebill1049** [comment]
thank you heaps @Argeare5 for the star and report the issue 🙏
