### ISSUE TITLE
Image not update when state changed

### ISSUE THREAD

**Issue by stpwin** [bluebill1049/react-simple-img#52]
`<SimpleImg height={300} src={this.state.uploadedUrl} />`

when this.state.uploadedUrl change image not updated.

**Comment by bluebill1049** [comment]
when are you changing the `src`? image already in the viewport or hasn't intersected?

**Comment by stpwin** [comment]
when I called function
```
setState({
uploadedUrl: "IMAGE_URL"
});
```

**Comment by bluebill1049** [comment]
so you want to change the image url after it's been lazy loaded?

**Comment by stpwin** [comment]
Yes I do.
I want to change src when I uploaded new profile picture.

**Comment by bluebill1049** [comment]
how about this approach:

https://codesandbox.io/s/6z3lx27p5z

**Comment by stpwin** [comment]
Thank you!

**Comment by bluebill1049** [comment]
please kindly leave a star if you find the package useful. many thanks :)

**Comment by juanpablocs** [comment]
please update codesandbox link, error 404.

i have same problem of image...

does not update the image when i change the props from my component
