### ISSUE TITLE
SSR: Prop `data-from-server` did not match

### ISSUE THREAD

**Issue by neighborhood999** [bluebill1049/react-simple-img#53]
Hi!

First, thanks for you create this awesome react component. I use this component in my next.js application and I got some error:

> Warning: Prop `data-from-server` did not match. Server: "yes" Client: "no"

I reproduce this error on the [Codesandbox](https://codesandbox.io/s/km36r3rmm7), please toggle to the `Console` to check this error message.

Thank you & Have a good day.

**Comment by bluebill1049** [comment]
Hey~!

Thank you for you kind words 🙏🏻i think i may have to remove this data-from-server logic... i will let you know, if i have an update on that. 

Thanks for reporting the issue ❤️

many thanks
bill

**Comment by bluebill1049** [comment]
hey

i have removed the data-from-server.

https://github.com/bluebill1049/react-simple-img/releases/tag/v2.1.8

let me know if that have resolved your issue.

many thanks
bill

**Comment by neighborhood999** [comment]
Hey @bluebill1049, thank you for quick fix issue, I updated the package and issue be fixed, thank you.

**Comment by bluebill1049** [comment]
謝謝 ❤️
