### ISSUE TITLE
Number.isNaN not supported in IE11

### ISSUE THREAD

**Issue by kyle-mccarthy** [bluebill1049/react-simple-img#54]
**Describe the bug**
Number.isNaN is not supported in IE11 but is used it https://github.com/bluebill1049/react-simple-img/blob/master/src/utils/getAspectRatio.js#L13

**Expected behavior**
Polyfill Number.isNaN or use alternative strategy

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] IE 11

**Comment by bluebill1049** [comment]
thanks for reporting :) https://github.com/bluebill1049/react-simple-img/releases/tag/v2.1.9

**Comment by kyle-mccarthy** [comment]
Thanks for resolving this so quickly! The new version resolves the problem.

**Comment by bluebill1049** [comment]
no worries :) please leave a star if u find this useful and support this component  ❤️

**Comment by bluebill1049** [comment]
thank you for the star and support ❤️
