### ISSUE TITLE
Image can't be loaded on FireFox

### ISSUE THREAD

**Issue by neighborhood999** [bluebill1049/react-simple-img#55]
![Kapture 2019-05-02 at 10 13 32](https://user-images.githubusercontent.com/10325111/57053854-50b56b00-6cc3-11e9-803e-b4639392f862.gif)

On FireFox(66.0.3), I scroll window and image can't be loaded. Not sure what happen, but on the Chrome works fine.

I'm not sure this problem is come from image source, because unsplash's image URL like `https://source.unsplash.com/collection/61/800x400` without file extension.

**Comment by bluebill1049** [comment]
can you take a look at the network tab? it works for me, I am using some free image service, images may come a bit slow.

**Comment by neighborhood999** [comment]
![Kapture 2019-05-02 at 10 46 21](https://user-images.githubusercontent.com/10325111/57054527-ad1a8980-6cc7-11e9-9533-6dbacfd02a6b.gif)

That's weird, images didn't be fetched.

**Comment by bluebill1049** [comment]
hmmmm... strange

**Comment by neighborhood999** [comment]
I reinstall my Firefox and try again. Thank you for quick reply @bluebill1049.

**Comment by bluebill1049** [comment]
![ezgif-2-6065635c5db7](https://user-images.githubusercontent.com/10513364/57054792-1efbce80-6cda-11e9-8546-d5a64bc8b815.gif)
should be ok tried mine here, let meknow if there still issues

**Comment by neighborhood999** [comment]
<img width="1552" alt="螢幕快照 2019-05-02 上午11 02 58" src="https://user-images.githubusercontent.com/10325111/57054888-f8359c00-6cc9-11e9-832f-06b805d8be8f.png">

I can sure this problem it's come from extension! All works fine for me now. XD

**Comment by bluebill1049** [comment]
谢谢了 哈
