### ISSUE TITLE
Inline CSS is stretching images

### ISSUE THREAD

**Issue by Alfrex92** [bluebill1049/react-simple-img#57]
Hi, in our company we have been using your library and it is working perfectly. 

However, we noticed that the inline CSS is stretching the images. 

 
![squeeze-img](https://user-images.githubusercontent.com/22891582/58322497-12434400-7e5c-11e9-94b1-d649cd366f4c.png)

We wrote the css that you need to add in order to avoid this problem. 

So, instead of using this
```

position: absolute;
    top: 0px;
    left: 0px;
    width: 100%;
    height: 100%;
```

You need to add this 

```
    position: absolute;
    left: -10000%;
    right: -10000%;
    top: -10000%;
    bottom: -10000%;
    margin: auto auto;
    min-width: 1000%;
    min-height: 1000%;
    object-fit:cover;
    -webkit-transform: scale(.1);
    transform: scale(.1);
```

Then, the image looks better.

![scale-img](https://user-images.githubusercontent.com/22891582/58322389-c8f2f480-7e5b-11e9-9db8-a1c04ea1010a.png)

You can see a live version of the technique here: [Mipon](http://mipon.org)

In case that you prefer keep using the same CSS, is it possible that we  can add our own css to the img? 

You can check this library as a reference:
https://github.com/reactjs/react-tabs/issues/148

The logic is the same, but the library allows to customize the CSS using StyledComponents.

Thanks! have a great weekend.

**Comment by bluebill1049** [comment]
hey,

can you try with `applyAspectRatio`?

**Comment by Alfrex92** [comment]
Yes, that's the prop that I'm using.

**Comment by bluebill1049** [comment]
oh ok, did you supply image `width` and `height` when you are using `applyAspectRatio`? For aspect ratio to work, it required to having image `width` and `height`. 

Yea, I think I can expose an image style prop, so you can apply your own style.

**Comment by Alfrex92** [comment]
Thanks for your quick response. Yes, I added the width and height when using applyAspectRatio. The library is working perfect. The CSS is what needs improvement. 

You can add replace the code for this: 

```
  position: absolute;
    left: -10000%;
    right: -10000%;
    top: -10000%;
    bottom: -10000%;
    margin: auto auto;
    min-width: 1000%;
    min-height: 1000%;
    object-fit:cover;
    -webkit-transform: scale(.1);
    transform: scale(.1);
```

Yess, it would be awesome if you can expose the style :D

**Comment by bluebill1049** [comment]
I will expose the style for you, I will work on it this week.

**Comment by bluebill1049** [comment]
can you try with `style` prop? looks like in my code accept style attribute.

`<SimpleImg style={style}} />`

**Comment by bluebill1049** [comment]
https://github.com/bluebill1049/react-simple-img/releases/tag/v2.3.0

you can try with `imgStyle`

**Comment by Alfrex92** [comment]
Hi, thanks for adding the new feature.

How can I use it?

like this?

```
 <SimpleImg
        src={
          ""
        }
        imgStyle={{
          position: "absolute"
        }}
      />
```

**Comment by bluebill1049** [comment]
Yes

**Comment by Alfrex92** [comment]
It's not working :S

https://codesandbox.io/s/lazyloadingsimplereactimg-58kwy

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/lazyloadingsimplereactimg-zpcvg
fixed
react-simple-img@2.3.1

**Comment by bluebill1049** [comment]
Hey,

Did you take another look?  please close the issue if its resolved

thanks
bill

**Comment by oquirozm** [comment]
@bluebill1049 this prop is super useful but I had to search through the issues to find it. Any chance it can be added to the documentation?

**Comment by bluebill1049** [comment]
sure @oquirozm u want to submit a PR to update readme?

**Comment by oquirozm** [comment]
@bluebill1049 sure, will do in a bit
