### ISSUE TITLE
Fallback/default img when img url is not valid

### ISSUE THREAD

**Issue by alfred-pb** [bluebill1049/react-simple-img#69]
**Is your feature request related to a problem? Please describe.**
Hi, there are some situations when the img url is invalid and it would great to handle those errors. 

**Describe the solution you'd like**
Add the onerror props to
 `<SimpleImg
onerror={}
/>`

For example:

`<img src="invalid_link" onerror="this.onerror=null;this.src='https://placeimg.com/200/300/animals';">
`
The above means that when the link is invalid will use a fallback img. 

You can find more info about onerror here:

[Inputting a default image in case the src attribute of an html <img> is not valid?](https://stackoverflow.com/questions/980855/inputting-a-default-image-in-case-the-src-attribute-of-an-html-img-is-not-vali
)
[How to handle loading images that does no exit](https://blog.imagekit.io/how-to-handle-loading-images-that-may-not-exist-on-your-website-92e6c3c6ea63)

**Comment by bluebill1049** [comment]
Hi @alfred-pb,

ideally, we should haven't invalid image URL in the first place. I think even more native <img /> tag, it just displays error image too.

can you write a function/Component to validate the image URL instead? you can write a component to wrap around the <SimpleImg /> to validate the image.

<ValidSimpleImg /> and have <SimgpleImg /> inside of it.

let me know you thoughts

cheers
bill

**Comment by ajisulist** [comment]
What if user failed to load the image. the url is valid but the image failed to load because of cdn down or connection lost

**Comment by bluebill1049** [comment]
@ajisulist same be behavior as native img. you can build a lot of stuff on the error and retry, but at the same time, it increases the complexity of this simple and small lib.

**Comment by bluebill1049** [comment]
going to close this issue, feel free to reopen if you have more questions.

**Comment by alfred-pb** [comment]
As @ajisulist  mentioned, the user might failed to load the image or the image doesn't exist yet in database. I think that adding an onError prop will be nice, instead of creating a function to validate the image URL. 

Is just allowing <SimpleImg> to receive the attribute ```onerror``` . That attribute is already built in the ```img``` tag so I don't think that is adding complexity to the lib. Don't you think?

**Comment by mousedown** [comment]
I agree , this would be great without having to wrap around another component.

**Comment by bluebill1049** [comment]
hmmm I think it's such easy piece of logic to do at your app level.

```
try {
  new url("xxx")
} catch {
  // not valid
} 
```
