### ISSUE TITLE
Add browser support to README

### ISSUE THREAD

**Issue by davidcetinkaya** [bluebill1049/react-simple-img#71]
**Is your feature request related to a problem? Please describe.**
I can see that the library is using the Intersection Observer API. Does that mean that browser support is equivalent to browsers that support Intersection Observer? Or do you use a polyfill?

**Describe the solution you'd like**
Add browser support list to README. This would allow developers browsing this library to instantly see what browsers are supported, and not have to look in the source code which can be time consuming.

**Comment by bluebill1049** [comment]
hey @davidcetinkaya 

it's already listed in the feature:

Simple usage and tiny size includes polyfill (minified + gzipped)

**Comment by davidcetinkaya** [comment]
Maybe I'm missing something very obvious 🙈, but where do you read that?

**Comment by bluebill1049** [comment]
feature list.

**Comment by bluebill1049** [comment]
Speed up initial page loads by loading only images above the fold
Responsive with placeholders and animations
Support Priority Hints with importance attribute
Smart download logic using IntersectionObserver
Simple usage and tiny size includes polyfill (minified + gzipped)

**Comment by davidcetinkaya** [comment]
Thanks for clarifying 🙂. Sorry, now I see 👍. Although I think something like this would help:

<img width="972" alt="2" src="https://user-images.githubusercontent.com/11529148/62192723-6d227b80-b376-11e9-8b63-dbac0f021e53.png">

**Comment by bluebill1049** [comment]
This package support majority of the browsers include ie11. But feel free to submit a PR to clarify this.

**Comment by davidcetinkaya** [comment]
Thank you. I have to try the library first in order to determine browser support and submit a PR.

**Comment by bluebill1049** [comment]
that would be lovely! thanks

**Comment by bluebill1049** [comment]
going to close this issue for now, feel free to send a PR to correct that in the near future
