### ISSUE TITLE
Using webp images with <picture> and multiple source sets?

### ISSUE THREAD

**Issue by andreimc** [bluebill1049/react-simple-img#72]
**Is your feature request related to a problem? Please describe.**

I would like to use react-simple image with webp as well: eg https://responsivedesign.is/articles/adding-webp-images-progressively/

**Describe the solution you'd like**

```
  <picture>
    <source type="image/webp"
            srcset="images/worlds-300.webp 300w,
                    images/worlds-600.webp 600w,
                    images/worlds-800.webp 800w,
                    images/worlds.webp 1000w"
             />
    <source srcset="images/worlds-300.jpg 300w,
                    images/worlds-600.jpg 600w,
                    images/worlds-800.jpg 800w,
                    images/worlds.jpg 1000w"
            />
    <img src="images/worlds-300.jpg"
    alt="The Speed of Light and the Timing of Eclipses" />
  </picture>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
Good suggestion, but I will start to work on that when `img` src tag support `webp`. Otherwise, it's a massive change inside the codebase to adopt <picture /> element.

**Comment by bluebill1049** [comment]
going to close this for now. until img src tag support webp
