### ISSUE TITLE
Typescript types generated ?

### ISSUE THREAD

**Issue by andreimc** [bluebill1049/react-simple-img#73]
**Is your feature request related to a problem? Please describe.**

I would love to use this in typescript, but has no types!

**Describe the solution you'd like**

Include types as part of the build

**Describe alternatives you've considered**

**Additional context**

**Comment by bluebill1049** [comment]
I am using flowtype in the project, you interested to submit a PR for typescript?

**Comment by bluebill1049** [comment]
feel free to submit PR for typescript
