### ISSUE TITLE
Height and width not accepting %

### ISSUE THREAD

**Issue by quochuy** [bluebill1049/react-simple-img#80]
**Describe the bug**
With 2.3.3 we used to be able to pass `height="100%"` but since height and width are now set as `number` this is now throwing a type error.

**To Reproduce**
`<SimpleImg
          src={src}
          height="100%"
          width="100%"
        />`

**Expected behavior**
Should allow us to use a string as well as number.

**Screenshots**
![Screen Shot 2019-09-17 at 11 43 10 am](https://user-images.githubusercontent.com/310654/65004607-5d6bf000-d940-11e9-8f41-3de884ed1d06.jpg)

**Comment by bluebill1049** [comment]
thanks the issue has been patched.
