### ISSUE TITLE
When Running Docker on LocalHost, Image Always Behind White Background

### ISSUE THREAD

**Issue by pkellner** [bluebill1049/react-simple-img#81]
This is really odd and I wish I had some obvious explanation (so I'm asking here in the hopes that it's some corner case needing fixing).

I create a very simple image tag with SimpleImg  as I'm showing below and what renders when I'm running docker locally is what is below that which shows no image because 1) it's hidden and 2) because it's hidden behind a white background.

Am I completely crazy? It works in docker production and it works when I run react in dev mode.

## tag on jsx page

```
<SimpleImg
                logConsoleError={true}
                alt={speakerName}
                src='/assets/images/speakers/speaker0.png'
                height={200}
                width={200}
            />
```

## rendered
```
<div
    style="position:relative;overflow:hidden;display:flex;flex-direction:column;justify-content:center;align-items:center;height:200px"
>
    <noscript
        ><img
            src="/assets/images/speakers/speaker0.png"
            alt="Manoj Agarwal"/></noscript
    ><img
        style="height:200px;width:200px;visibility:hidden"
        alt="Manoj Agarwal"
        src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
        srcset=""
        data-src="/assets/images/speakers/speaker0.png"
    />
    <div
        style="position:absolute;top:0;left:0;width:100%;height:100%;background:white;transition:0.3s opacity"
    ></div>
</div>
```

**Comment by bluebill1049** [comment]
you can remove the placeholder by setting `placeholder={false}` which is the `src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="` white background

**Comment by bluebill1049** [comment]
feel free to re-open if you have more questions
