### ISSUE TITLE
threshold doesn't take in account scrolling down

### ISSUE THREAD

**Issue by younes0** [bluebill1049/react-simple-img#84]
Threshold should take in account, the lower part of the image which would the only visible part when scrolling from down.

Not sure how you could do this with one IntersectionObserver, you would need two with different roots maybe?

**Comment by bluebill1049** [comment]
react simple img is based on `IntersectionObserver` and I am not sure to introduce the additional features on top of it just yet.

**Comment by younes0** [comment]
I understand, but shouldn't be lazyLoading be effective on any scroll direction ?

**Comment by bluebill1049** [comment]
last time I tested it was working for me.

**Comment by bluebill1049** [comment]
gong to close this issue for now, unless someone wants to contribute

**Comment by younes0** [comment]
> last time I tested it was working for me.

All right then.
I'm using react simple img inside a Carousel which is not the conventional way of using the library :)
