### ISSUE TITLE
Placeholder does not have `alt` attribute

### ISSUE THREAD

**Issue by xxczaki** [bluebill1049/react-simple-img#90]
**Describe the bug**
When I test my site using [Lighthouse](https://developers.google.com/web/tools/lighthouse), either in the browser or using ex. [the web.dev platform](https://web.dev/measure/), I get a lower score in Accessibility, as well as SEO.

![](https://imgur.com/2s6FKkp.png)
![](https://imgur.com/eDFos3G.png)

When I click on `img` on the `Failing Elements` list, it shows the exact element that fails:

![](https://imgur.com/vfenwXM.png)

By the look of things, it is the SVG placeholder.

**To Reproduce**

##### using Chrome browser (recommended)
1. Go to [kepinski.me](https://kepinski.me) in incognito mode
2. Open DevTools
3. Go to the `Audits` tab
4. Use the default configuration & click on the `Run audits` button
5. Wait for the audits to complete & see warnings

##### using web.dev platform
1. Go to [web.dev](https://web.dev/measure)
2. In the `Enter a web page URL` input enter `https://kepinski.me`
3. Click on the `Run audit` button
5. Wait for the audit to complete & see warnings

**Expected behavior**
The placeholder should have an `alt` attribute so that Lighthouse would not report any warnings related to that.

**Screenshots**
Already included them above.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 (Xfce, 64-bit)
 - Browser: Chrome
 - Version: 79.0.3945.88

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
Here is my image component (which uses `react-simple-img`): https://github.com/xxczaki/kepinski.me/blob/37ba4c1e1a5ac2fafc494e93e38de1376ad439c8/components/me.js#L17

**Comment by bluebill1049** [comment]
thanks @xxczaki for the issue report. want to submit a PR for this fix?

**Comment by xxczaki** [comment]
@bluebill1049 Sure, here is the fix: #91 :smile:
