### ISSUE TITLE
Images loaded over network twice with cache disabled 

### ISSUE THREAD

**Issue by mousedown** [bluebill1049/react-simple-img#95]
**Describe the bug**
Images appear to be loaded over the network twice when you disable cache (via chrome dev tools). once via fetch and another via the loader. 

**To Reproduce**
1. Visit https://react-simple-img.herokuapp.com/
2. Disable Cache
3. Scroll down to reveal images
4. Inspect Network tab 

**Expected behavior**
Images should only be downloaded once 

**Screenshots**
<img width="1104" alt="Screenshot 2020-04-22 at 15 16 43" src="https://user-images.githubusercontent.com/491789/79993163-5bf14000-84ac-11ea-8551-345c2aca67bf.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : Chrome

**Additional context**
This is worse in my project that I'm working on., I suspect because i am not using service workers. With caching enabled, the second request for the image is retrieved from memory. Is there a way to prevent the second load with caching disabled?

**Comment by bluebill1049** [comment]
hey @mousedown any chance you can look into this at the code level, i am pretty busy with another project at the moment, i will take me sometimes to come back to this.

**Comment by mousedown** [comment]
Sure! I will do one day, but I am also flat out with a project. I see this as an optimisation and way down on my list.

**Comment by bluebill1049** [comment]
awesome thanks mate.

**Comment by jhodges10** [comment]
I've seen this happen before with another image library, I think the bug is upstream somewhere.
