### ISSUE TITLE
When Component Re-Renders with new src tag, image does not change.

### ISSUE THREAD

**Issue by pkellner** [bluebill1049/react-simple-img#96]
I have the following component that I know the src is changing because if I swap <SimpleImg for <img the image changes as I would expect.  It appears react-simple-img is caching the image the first time it was loaded.

```
import React from 'react';
import { SimpleImg } from 'react-simple-img';
import { ThemeContext, THEMELIST } from '../../contexts/ThemeContext';

function SpeakerImage({ id }) {
  const { theme } = React.useContext(ThemeContext);

  console.log(`SpeakerImage: id: ${id}   theme: ${theme}`);

  const imageUrl =
    theme === THEMELIST.DARK
      ? `/speakers-bg-gray-500/speaker-${id}.jpg`
      : `/speakers/speaker-${id}.jpg`;

  return (
    <>
      {theme} {imageUrl}
      <SimpleImg
        src={imageUrl}
        animationDuration='1'
        width={200}
        height={200}
        applyAspectRatio='true'
      />
    </>
  );
}

export default SpeakerImage;
```

**Comment by bluebill1049** [comment]
I would switch to normal `<img />` tag when src is changing, currently, this lib doesn't support src changing. (I don't think i have time to include this new feature either :(

**Comment by pkellner** [comment]
Thanks @bluebill1049 I don't really understand the issue, but I do notice that data-src changes, just not src. Does that make sense why it is happening? (I love how it works otherwise)

**Comment by vunguyentuan** [comment]
@pkellner you can pass a key to trigger re-render

**Comment by mangojai** [comment]
I cannot get a key=uuid working to rerender. how can I substitute an img tag instead of src?
I have auto dark mode feature and wish to change the image based on dark or light preference. Any help appreciated!
